# Create a new consumer
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "Jane Doe",
  "username": "janedoe",
  "email": "jane@example.com",
  "password": "password123",
  "role": "consumer",
  "address": "456 Main St, Tel Aviv"
}

###

# Create a new consumer
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "John Doe",
  "username": "johndoe",
  "email": "noaha@gmail.com",
    "password": "password123",
    "role": "supplier",
    "address": "789 Maple St, Tel Aviv"
}

###

# Create a new order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "consumerId": "677e751a6466a7a72d20ac5e",
  "supplierId": "677e766f63cb14842d0a7165",
  "status": "pending",
  "deliveryAddress": "123 Elm St, Tel Aviv",
  "deliveryTime": "2025-01-10T15:30:00.000Z"
}

###

# Create a new group
POST http://localhost:3000/groups
Content-Type: application/json

{
  "supplierId": "677e766f63cb14842d0a7165",
  "region": "Tel Aviv",
  "status": "active",
  "orders": []
}

###

# Get all users
GET http://localhost:3000/users

###

# Get all orders
GET http://localhost:3000/orders

###

# Get all groups
GET http://localhost:3000/groups
